### ISSUE TITLE
Enable eslint and solhint

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-community-contracts#36]
To replicate @openzeppelin/contracts linting, we should enable eslint and solhint with the same settings.

The `checks/eslint-solhint` branch includes some of the requested changes. However some issues remain:
- Disable solhint checks on the vendor contract 
  - the glob approach used for prettier doesn't apply
  - Make sure this also applies to lint-staged
- copy vs link to config files in the submodule

**Comment by arr00** [comment]
Fixed in #39
