### ISSUE TITLE
Account Abstraction: fix execution

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-community-contracts#48]
Currently, `AccountCore` implements `executeUserOp` using a `Address.functionCallWithValue`.

This causes multiple issues:
- if the target is an EOA, `verifyCallResultFromTarget` will revert with `AddressEmptyCode`. This prevents the account from sending Eth to an EOA.
- it is not possible to batch transaction in one user operation. ERC-7579 supports that, but the AccountCore does not. 
  - Adding multicall is not an acceptable approach. The `executeUserOp --[call]--> multicall --[delegate] --> executeUserOp` is to much to handle (huge multicall containing fake userops).
  
A proposal of fix would be:

- In `AccountCore` (see [this](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5250/files#diff-52e99bab868addbfbac354587d8e48634881e5ef6060dc03a2a749968d6fc487R98-R103))
```
function executeUserOp(
        PackedUserOperation calldata userOp,
        bytes32 /*userOpHash*/
    ) public virtual onlyEntryPointOrSelf {
        Address.functionDelegateCall(address(this), userOp.callData[4:]);
    }
```
- In `Account` add an opinionated `execute(address,uint256,bytes) public onlyEntryPointOrSelf()` that implements the current behavior of `executeUserOp` (with a fix to support sending eth to EOAs)
  - by default, the AccountCore would not be able to do external calls. This will have to be documented
  - alternative is to use ERC-7579's `execute(bytes32 mode, bytes calldata executionCalldata)`
  
- In `Account`: inherit from `Multicall`
  - that would implement the `executeUserOp --[delegate]--> multicall --[delegate] --> execute` with efficient calldata.

**Comment by Amxx** [comment]
EDIT:

We can actually keep the "call" behavior in `executeUserOp`, and if we have `multicall` and `execute` we can still do

```
// single
entrypoint --[call]--> executeUserOp --[call]--> (target)
entrypoint --[call]--> execute --[call]--> (target)
// multicall
entrypoint --[call]--> executeUserOp --[call]--> multicall --[delegate] --> execute --[call]--> (target)
entrypoint --[call]--> multicall --[delegate] --> execute --[call]--> (target)
```

**Comment by frangio** [comment]
There needs to be a standard `execute` function. ERC-7579 is one option. [ERC-7821](https://ercs.ethereum.org/ERCS/erc-7821) has taken that interface and standardized it separately without.
